# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A0Ojl2hw_OPCnJVSp-TdoexQ3On-0IBv
"""

import pandas as pd

import numpy as np

import seaborn as sns

from google.colab import drive



drive.mount('/content/drive')

df = pd.read_excel(r'/content/drive/MyDrive/energydata_complete.xlsx')

part_df = df[["T6","T2"]]

y = df.T6

x = part_df[["T2"]]

from sklearn.metrics import r2_score

r2_score = r2_score(y,x)

round(r2_score,3)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

from sklearn.model_selection import train_test_split

x = df.iloc[:,1:]
y = df['Appliances']

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

x_train.shape,x_test.shape

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()   

scaler.fit(x_train)       

x_train_scaled = scaler.transform(x_train)    
x_test_scaled = scaler.transform(x_test)

x_train_scaled = pd.DataFrame(x_train_scaled,columns = x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled,columns = x_test.columns)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
features_df = normalised_df.drop(columns=['date', 'lights'])